### ISSUE TITLE
Restrict the replacement of text for specific URL, html-element, etc.

### ISSUE THREAD

**Issue by tarikmustafic** [Appdynamics/demomonkey#37]
It would be great to have an option to restrict the replacement of text within demo monkey for only specific URL, html-element, etc. Often I click through different pages during a demo and on one page I need one text replacement and on the other I need something different to be shown.

**Comment by svrnm** [comment]
The upcoming release will contain a `!replace` command, that allows you to call text search and replace explicitly:

```ini
!replace(AD-, APPS_ALL_DASHBOARD) = BC-
```

A css filter will follow later.
