### ISSUE TITLE
Force the connection status with appdynamics.replaceFlowmapConnection

### ISSUE THREAD

**Issue by jeromeguillaume** [Appdynamics/demomonkey#42]
Can we adapt appdynamics.replaceFlowmapConnection to force the change of connection even if AppD shows "not comparing against Baseline data"?

It will be easier to demonstrate the benefit of the flow map (concerning, per example, the Checkout BT)

**Comment by svrnm** [comment]
@jeromeguillaume - I will look into this, probably the easiest way is setting a parameter in the command to force the replacement.

Thanks!

**Comment by svrnm** [comment]
@jeromeguillaume - added this, was easy;-) Will be included in the next release.
