### ISSUE TITLE
DEV - Extension UI On/Off Toggle

### ISSUE THREAD

**Issue by csek06** [Appdynamics/demomonkey#43]
Dev build. 
UI doesn't update to reflect toggling on/off until you click away from the extension and then click back into the extension.
![screen shot 2018-08-29 at 1 52 48 pm](https://user-images.githubusercontent.com/29148599/44807747-57ba3580-ab98-11e8-8c15-26fdb184371b.png)

**Comment by svrnm** [comment]
@csek06 Do you still experience this issue with the dev build? I updated it a few times and I can not reproduce the issue.

**Comment by csek06** [comment]
Seems to be resolved.
