### ISSUE TITLE
Add ability to replace flowmap circle colors

### ISSUE THREAD

**Issue by riesgo** [Appdynamics/demomonkey#48]
Would like to be able to change flowmap circle colors to show severity of BT traffic with both nodes and business transactions colors in circle.  This, in combination with replaceFlowmapConnection lets me paint a nice picture of a slow backend somewhere down the line causing issues on front end services.

![image](https://user-images.githubusercontent.com/10291938/60399871-c742dd80-9b39-11e9-87f9-ee20f8dab9b1.png)

![image](https://user-images.githubusercontent.com/10291938/60399900-6ff13d00-9b3a-11e9-898a-958725373928.png)

![image](https://user-images.githubusercontent.com/10291938/60399923-9ca55480-9b3a-11e9-9ce4-86817ed55d18.png)

Minimal would be inner circle, that would help a lot!

**Comment by svrnm** [comment]
Thanks for opening this (overdue) ticket! Yes, case 2 (outer circle) is a little bit tricky, since it's not easily to color, but I can have a look into the inner circle

**Comment by svrnm** [comment]
Hey, can you install http://bit.ly/demomonkey-dev and check if the following commands to the trick:

!appdynamics.replaceInnerNodeHealth(nodename) = critical
!appdynamics.replaceOuterNodeHealth(nodename) = critical

You can use normal, warning or critical as value (actually you can give a color also;-))

The replaceOuterNodeHealth is a little bit tricky to use, it will replace all normal nodes with the value you give, except you provide an additional parameter:

!replaceOuterNodeHealth(nodename, warning) = critical

this will also turn all yellow nodes into red.

**Comment by riesgo** [comment]
Looks good!

Some of the outter colors are not changing, but AWESOME!!!
Checkout the OrderProcessing and QuoteServices outter colors.  I was able to get them to change by using the "!replaceOuterNodeHealth(nodename, warning) = critical" with extra param in there.

before:
![image](https://user-images.githubusercontent.com/10291938/60747202-acb19f80-9f51-11e9-84ab-dfa50779f1fb.png)

after:
![image](https://user-images.githubusercontent.com/10291938/60747159-4a589f00-9f51-11e9-80ca-13729c60fdce.png)

these are my entries for AD-Financial on Demo2.

`[AD Financial - flowmap colors]

;
; WebFrontEnd Tier colors
;
!appdynamics.replaceInnerNodeHealth(WebFrontEnd) = critical
!appdynamics.replaceOuterNodeHealth(WebFrontEnd) = warning

;
; WebFrontEnd -> OrderProcessing & QuoteServices - turn it all green
;
!replaceFlowmapConnection("WebFrontEnd", "OrderProcessing") = Normal
!replaceFlowmapConnection("WebFrontEnd", "QuoteServices") = Normal
;!replaceFlowmapConnection(QuoteServices,"MySQL - StockDB") = Normal

!replaceInnerNodeHealth(OrderProcessing) = normal
!replaceOuterNodeHealth(OrderProcessing) = normal
!replaceInnerNodeHealth(QuoteServices) = normal
!replaceOuterNodeHealth(QuoteServices) = normal
;!replaceOuterNodeHealth(QuoteServices, critical) = warning

;
; WebFrontEnd -> AccountManagement - turn line yellow and colors yellow, leave red alone.
;
!replaceFlowmapConnection("WebFrontEnd", "AccountManagement") = Warning
!replaceInnerNodeHealth(AccountManagement) = warning
!replaceOuterNodeHealth(AccountManagement, normal) = warning
;
; Rename CreditCheck app going to different controller to less ugly name.
;
AD-CreditCheck-Demo2@customer1 = AD-CreditCheck-App

;
; LoanServices -> AD CreditCheck App
;
!appdynamics.replaceInnerNodeHealth(LoanServices) = warning
!replaceFlowmapConnection("AccountManagement",LoanServices) = Warning
!replaceFlowmapConnection(LoanServices,AD-CreditCheck-App) = Critical

; !replaceFlowmapConnection(PaymentServices,AD-CreditCheck-Demo2@customer1) = Critical

;
; Change AD CreditCheck App colors
;
!replaceInnerNodeHealth(AD-CreditCheck-App) = critical
!appdynamics.replaceOuterNodeHealth(AD-CreditCheck-App) = warning

`

**Comment by svrnm** [comment]
fixed.
