### ISSUE TITLE
Lambda icon support

### ISSUE THREAD

**Issue by adamjsr** [Appdynamics/demomonkey#50]
Add support for replacing node type icon with Lambda icon.

**Comment by svrnm** [comment]
That's already implemented and will come with the next release:

```ini
!appdynamics.replaceNodeCount(serviceName) = lambda
```

To try it out, use the dev-channel: https://bit.ly/demomonkey-dev

**Comment by svrnm** [comment]
This is no part of the stable release, issue fixed, please re-open if you are facing any further issues.
