### ISSUE TITLE
Add ability to change Tiers and Nodes amount

### ISSUE THREAD

**Issue by andyrlv** [Appdynamics/demomonkey#53]
Would like to change the both amount of Tiers and Nodes in Downstream business application. Right now, it possible to change only upper number using the following construction:

`!replaceNeighbor(ECommerce-Fullfilment, 2, text.adsNodeCountText) = 5`

<img width="447" alt="Screenshot 2019-10-18 at 11 39 39" src="https://user-images.githubusercontent.com/56718169/67079634-35b8b380-f19c-11e9-8876-b37ffcf2b38a.png">

**Comment by svrnm** [comment]
Referenced wrong ticket in commit 049a9d12ced6cd6c98518213ddef23462d67ac59, added the capability to replace tiers and nodes on application nodes.
