### ISSUE TITLE
Change the icon of Drill down in snapshot

### ISSUE THREAD

**Issue by jeromeguillaume** [Appdynamics/demomonkey#54]
My use case is the following: this Tier takes only 0.1% of time and this tier has a green Outer status. So there is no reason to make a drill down. It should be the green icon

<img width="215" alt="drilldown" src="https://user-images.githubusercontent.com/4004310/67085567-559da680-f19f-11e9-935c-569fffdfe283.png">

**Comment by svrnm** [comment]
6.0.0 contains this as a feature.
