### ISSUE TITLE
Hide Application and Remote Service on Flow Map

### ISSUE THREAD

**Issue by jeromeguillaume** [Appdynamics/demomonkey#57]
Hello,

The functions `!hideApplication` & `!hideRemoteService` hide correctly the App on 'Applications' page and the Remote Service on 'Remote Services' page. But the the App and Remote Service are still present on Flow Map.

Enhancement: extend the capability of `!hideApplication` & `!hideRemoteService` to hide App & Remote Service on Flow Map

In screenshot we would like to hide 'ZED - Gerfo' and 'SharePoint Search'

Thanks
<img width="410" alt="Capture d’écran 2019-10-28 à 11 11 01" src="https://user-images.githubusercontent.com/4004310/67670188-acf7ff80-f973-11e9-9be5-24e73f7f03bf.png">

**Comment by svrnm** [comment]
This behaviour is intended, since you can use the flowmap editor to hide elements... except the application... so you are right, it might be better to have that consistency.
