### ISSUE TITLE
Sync Scripts with Team/Group

### ISSUE THREAD

**Issue by csek06** [Appdynamics/demomonkey#59]
With the new Sync feature coming, it would be nice to include the ability for a group to sync their scripts together to increase collaboration and reduce individual efforts.

**Comment by svrnm** [comment]
I just created a project within this github repo to lay out all the features that I plan to have for teams:

https://github.com/Appdynamics/demomonkey/projects/1

**Comment by svrnm** [comment]
Since I tried this over and over again without success, I decided to not add syncing features. Won't fix.
