### ISSUE TITLE
Allow different configurations to be applied to the same page in different tabs at the same time

### ISSUE THREAD

**Issue by adamjsr** [Appdynamics/demomonkey#61]
I want to be able to apply a single configuration to a page, and then apply a different configuration to another instance of the same page in a different tab, so that both instances of the page can display the same element but styled differently when I switch back and forth between the page instances.  I don't see a way to do this.

**Comment by svrnm** [comment]
That's an interesting one.

What would your use case be for that? Can you give me a concrete example?

**Comment by svrnm** [comment]
Is this still a relevant topic @adamjsr ? You can of course achieve that by adding some words to the URL behind the # or ? and check for the existence of them, but if you could give me more details on your use case I could look into it.
