### ISSUE TITLE
Want to change the colors in dark mode

### ISSUE THREAD

**Issue by kentonself-appdynamics** [Appdynamics/demomonkey#63]
Editor colors look too dark. Prefer something else.

My code is available for this.

![03_54_22](https://user-images.githubusercontent.com/42982948/77009730-6c0a8280-6936-11ea-8f5b-fd843c99cfcd.jpg)
![03_56_37](https://user-images.githubusercontent.com/42982948/77009732-6e6cdc80-6936-11ea-82ff-bd97b0ec427a.jpg)

**Comment by svrnm** [comment]
Fixed with #64
