### ISSUE TITLE
Add ability to delete nodes & edges in Experience Journey Map

### ISSUE THREAD

**Issue by adamjsr** [Appdynamics/demomonkey#76]
I'd like the ability to remove nodes (and their associated edges) from the Experience Journey Map.  If I remove a node that is not the terminal node in a particular journey, ideally the remaining edges will be updated/reconnected automatically so as not to leave any 'gaps' in the map.

**Comment by svrnm** [comment]
This is not easily achievable as of right now. I will keep this ticket open as a reminder.
