### ISSUE TITLE
Tags for different XArch Configs / Dashboard specifc scripts

### ISSUE THREAD

**Issue by BlincoeAppD** [Appdynamics/demomonkey#77]
Ability to tag scripts to for easy filtering.

Examples tags:
XArch Product
Dashboard specific
Demo Environment
Technology

**Comment by svrnm** [comment]
I added functionality that tags are extracted from your configurations:

First add tags to your demo config:
```
@tags[] = .net, movetickets
@tags[] = demo2, DCI
```
then search for those terms

note that tags can not contain spaces, are case insensitive and are not matched partially.
