### ISSUE TITLE
Comprehensive Help Guide with Example Commands

### ISSUE THREAD

**Issue by clintonfray** [Appdynamics/demomonkey#83]
Provide a help guide showing the various commands with examples on how to use them.

**Comment by stevar00** [comment]
Upvote on this - or at least post some examples of .monkey files.

**Comment by svrnm** [comment]
I extended the USAGE.md: https://github.com/Appdynamics/demomonkey/blob/master/USAGE.md -- is this helpful already? I might extend it even further with some screenshots etc later on

**Comment by clintonfray** [comment]
This is perfect, just what I was looking for. Thank you @svrnm
