### ISSUE TITLE
More usage examples for commands

### ISSUE THREAD

**Issue by ClydeDz** [Appdynamics/demomonkey#87]
Hi,

I really like where DemoMonkey can be used. I personally use DemoMonkey to hide my email address during demo's, etc. Having said that, for other use cases it's a bit difficult to understand how to use it. For example, I was trying to use `!redirectUrl(url) = newURL` but haven't really got it working and I'm not what's wrong. Would be great to have more examples to follow.

Could you please include more examples in the usage document around the [commands](https://github.com/Appdynamics/demomonkey/blob/master/USAGE.md#commands)?

Thanks!

**Comment by svrnm** [comment]
Hi,

updating the examples / usage section is on the agenda, see also at #83

Rg. redirectUrl: There are 3 things you need to make sure:

- Go to settings and turn on the WebRequest Hook
- Add the url (or parts of it) to your @include 
- Make sure that you either match the URL exactly or that you use `*` as a wildcared.

I hope that helps,

Severin

**Comment by svrnm** [comment]
I extended the USAGE.md: https://github.com/Appdynamics/demomonkey/blob/master/USAGE.md -- is this helpful already? I might extend it even further with some screenshots etc later on

**Comment by svrnm** [comment]
@ClydeDz please check the updates I did to the USAGE.md, note that I moved the repository to https://github.com/svrnm/DemoMonkey, feel free to open another issue if needed

**Comment by ClydeDz** [comment]
Thanks, @svrnm!
